### ISSUE TITLE
More tab syncing!

### ISSUE THREAD

**Issue by juliasilge** [rstudio/vetiver.rstudio.com#22]
The tabs are better than before #19 but we still experience a bit of weirdness:

https://user-images.githubusercontent.com/12505835/170309770-ced2f716-9f2c-4be2-88ce-023cc9db553e.mp4

(Video thanks to Garrick)

Here are the steps for me to see this:

- Go to https://rstudio.github.io/vetiver.rstudio.com/get-started/version
- R is chosen by default
- Click on Python on the first tabset
- The second tabset now _says_ Python is chosen but the content shown is the R content

@dpastoor This isn't super urgent but if you get a chance soon, can you take a look at this?

**Comment by dpastoor** [comment]
Got it cleanly working!

https://user-images.githubusercontent.com/3196313/173242877-42ef7034-e739-4bc0-aaec-cf3dadc668e8.mov

PR incoming
