### ISSUE TITLE
Update parity checklist for new version of Python vetiver

### ISSUE THREAD

**Issue by juliasilge** [rstudio/vetiver.rstudio.com#25]
We need to update here for the newest version of vetiver for Python: 
https://vetiver.rstudio.com/learn-more/parity-checklist.html

@isabelizimm can you either do this or pass this on to someone else with the needed info?

**Comment by isabelizimm** [comment]
I can update the `.qmd`, if you can you re-render after?

**Comment by juliasilge** [comment]
Absolutely
