### ISSUE TITLE
gh actions to render site

### ISSUE THREAD

**Issue by isabelizimm** [rstudio/vetiver.rstudio.com#33]
Quarto has [github actions functionality](https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-01-basics.md)-- it seems like we are pretty close to being able to delegate rendering + publishing to GHA on the vetiver site. 

There are a few things that are currently not automated, that are blocking this:

- [ ] creating new plot for python monitoring (probably can become automated)
- [ ] awkward code chunk breaks when `output: false` 
- [ ] anything else?

It makes some sense to me to render the site with actions currently, even though we have longer-term goals to bring the API docs onto the site (which will be a little more complex with actions). WDYT?

**Comment by juliasilge** [comment]
I think this is a great idea! 🙌 If you want to start setting it up, I can do a review or give feedback.
