### ISSUE TITLE
Add more details about vetiver.load_pkgs()...

### ISSUE THREAD

**Issue by coforfe** [rstudio/vetiver.rstudio.com#53]
Hi,

I tried with several different alternatives how to use `vetiver.load_pkgs() to generate a vetiver_requirements.txt` and then build a Docker, but I get constant errors.

Please could you expand the documentation for that function.

I tried these alternatives:

```python
from vetiver import load_pkgs

load_pkgs()
load_pkgs(model_board)
load_pkgs(app_file)
```
And they produced several kind of erorrs...

The only one that worked was:

```python
from vetiver import load_pkgs

load_pkgs(v)
```
It run but generated this message  `pip-compile: command not found` and there is no new file the `vetiver_requirements.txt`.

Thanks a lot for **vetiver** it makes really easy how to expose and deploy a model!
Carlos.

**Comment by isabelizimm** [comment]
Hi Carlos--

[load_pkgs](https://rstudio.github.io/vetiver-python/stable/reference/vetiver.load_pkgs.html?highlight=load_pkgs) does take a VetiverModel as input, but, thank you for mentioning that this may not be very obvious! I'll update the docs to help out the next user 👍 

This error occurs if `pip-tools` is not installed. If you're on an earlier version of vetiver, that might be the case as it started out as an optional install. Try out `pip install vetiver --upgrade`, or just `pip install pip-tools` and let me know if this error persists!

**Comment by coforfe** [comment]
Thanks Isabel,
I will give you details if I can complete the example with your references.

Thanks again,
Carlos.

**Comment by isabelizimm** [comment]
Hi Carlos-- 
The docs for `load_pkgs` are searchable and also on the main page (https://rstudio.github.io/vetiver-python/latest/). I'm closing this issue, but please let me know if you have any other concerns!

**Comment by coforfe** [comment]
Hi Isabel,
Thanks. 
I could not reivew this again, I will get back if i find any more issues.

Thanks again,
Carlos.
