### ISSUE TITLE
Documentation Site `vetiver.posit.co` 404

### ISSUE THREAD

**Issue by z02dpj** [rstudio/vetiver.rstudio.com#80]
At the time of this writing, https://vetiver.rstudio.com/ and https://vetiver.posit.co/ return a 404 error for page not found.

**Comment by juliasilge** [comment]
Thanks for the report!

Currently building some changes in c7383d7d007db64516a5f8a94b7850664567c798 🤞

**Comment by juliasilge** [comment]
The site is now back up: <https://vetiver.posit.co>

Thanks you very much for the report! 🙌
